[package]
name = "checkers-abi"
version = "0.1.0"
edition = "2021"

[dependencies]
linera-sdk.workspace = true
async-graphql.workspace = true
serde.workspace = true
bcs.workspace = true

[dev-dependencies]
linera-sdk = { workspace = true, features = ["test"] }
